version: '3.8'

networks:
  aw-network:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:

services:

  api-avaliacao:
    build:
      context: ./avaliacao
      dockerfile: ./avaliacao/Dockerfile
    image: phpimentel/api-avaliacao:v1
    ports:
      - "8090:8090"
    networks:
      - aw-network

  api-produtos:
    build:
      context: ./produto
      dockerfile: ./produto/Dockerfile
    image: phpimentel/api-produtos:v1
    ports:
      - "8080:8080"
    networks:
      - aw-network
    depends_on:
      - "api-avaliacao"

  prometheus:
    image: prom/prometheus:v2.24.1
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - aw-network
    ports:
      - '9090:9090'
    depends_on:
      - "api-produtos"

  grafana:
    image: grafana/grafana:9.4.7-ubuntu
    ports:
      - '3000:3000'
    networks:
      - aw-network
    depends_on:
      - "prometheus"