global:
  scrape_interval: 5s
  scrape_timeout: "5s"
  evaluation_interval: "15s"

scrape_configs:
  - job_name: "api-produtos-job"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["api-produtos:8080"]
        labels:
          application: "api-produtos"